### PR TITLE
Dependency and small config.h cleanup

### PR DESCRIPTION
**Pull request by digiexchris**
Got it compiling on a brand new dev install, needed to swap out some dependencies for compatible ones and changes of repo name.

The cmake files are for if people want to use the esp-idf toolchain, it should be mostly compatible with platformio, so you can use both at the same time.

Also did a first pass at sorting variables into spaces that own them, with the idea that we can wrap abstractions around these and making these areas easier to extend and modify in the future. I see that your current commit also does the majority of this for me, so I just took it a tiny bit further. Also for memory safety and thread safety reasons. This isn't a complete refactor, but just what I did while I was dealing with the dependency updates. It cleans up the config.h, but it spreads includes around. I think this is a necessary evil at this stage, because it helps us see what's coupled to what, and what could be decoupled from what. Other alternatives are a precompiled header, with a .inl that goes along with it for the variable initialization. 

But honestly, I think a lot of this is solved by separating concerns into their own classes with their own private internal state. I'll post an issue up with those thoughts separately.

Not done yet: moving the libs into the repo and committing them.

### CODE REVIEW

**Comment by digiexchris** [comment]
oh I should mention that while it compiles, I have not tested it on my bench setup  yet. I will do that tonight.

**Comment by jschoch** [comment]
I'll do some testing tonight on it!!!

**Comment by jschoch** [comment]
this stepper lib doesn't have rmt, we want

 :gin66/FastAccelStepper@^0.28.3

**Comment by jschoch** [comment]
not compiling...  again c/c++ builds mystify me.  missing some flag or something vs Cmake?

```
src/src/Stepper.cpp:42:8: error: conflicting declaration 'double jog_mm'
 double jog_mm = 0;
        ^~~~~~
In file included from src/src/Stepper.cpp:5:
src/src/state.h:10:24: note: previous declaration as 'volatile double jog_mm'
 extern volatile double jog_mm;
                        ^~~~~~
src/src/Stepper.cpp:111:5: error: redefinition of 'int timertics'
 int timertics = 10;
     ^~~~~~~~~
src/src/Stepper.cpp:14:5: note: 'int timertics' previously defined here
 int timertics = 10;
     ^~~~~~~~~
src/src/Stepper.cpp:115:14: error: redefinition of 'volatile int delta'
 volatile int delta = 0;
              ^~~~~
src/src/Stepper.cpp:18:14: note: 'volatile int delta' previously defined here
 volatile int delta = 0;
              ^~~~~
src/src/Stepper.cpp:118:14: error: redefinition of 'volatile int delay_ticks'
 volatile int delay_ticks = 3;
              ^~~~~~~~~~~
src/src/Stepper.cpp:21:14: note: 'volatile int delay_ticks' previously defined here
 volatile int delay_ticks = 3;
              ^~~~~~~~~~~
src/src/Stepper.cpp:119:14: error: redefinition of 'volatile int previous_delay_ticks'
 volatile int previous_delay_ticks = 0;
              ^~~~~~~~~~~~~~~~~~~~
src/src/Stepper.cpp:22:14: note: 'volatile int previous_delay_ticks' previously defined here
 volatile int previous_delay_ticks = 0;
              ^~~~~~~~~~~~~~~~~~~~
src/src/Stepper.cpp:120:14: error: redefinition of 'volatile int min_delay_ticks'
 volatile int min_delay_ticks = 5;
              ^~~~~~~~~~~~~~~
src/src/Stepper.cpp:23:14: note: 'volatile int min_delay_ticks' previously defined here
 volatile int min_delay_ticks = 5;
              ^~~~~~~~~~~~~~~
src/src/Stepper.cpp:123:14: error: redefinition of 'volatile int jog_delay_ticks'
 volatile int jog_delay_ticks = 0;
              ^~~~~~~~~~~~~~~
src/src/Stepper.cpp:26:14: note: 'volatile int jog_delay_ticks' previously defined here
 volatile int jog_delay_ticks = 0;
              ^~~~~~~~~~~~~~~
src/src/Stepper.cpp:125:15: error: redefinition of 'volatile bool z_dir'
 volatile bool z_dir = true; //CW
               ^~~~~
src/src/Stepper.cpp:27:15: note: 'volatile bool z_dir' previously defined here
 volatile bool z_dir = true; //CW
               ^~~~~
src/src/Stepper.cpp:126:15: error: redefinition of 'volatile bool z_prev_dir'
 volatile bool z_prev_dir = true;
               ^~~~~~~~~~
src/src/Stepper.cpp:28:15: note: 'volatile bool z_prev_dir' previously defined here
 volatile bool z_prev_dir = true;
               ^~~~~~~~~~
src/src/Stepper.cpp:127:15: error: redefinition of 'volatile bool z_moving'
 volatile bool z_moving = false;
               ^~~~~~~~
src/src/Stepper.cpp:29:15: note: 'volatile bool z_moving' previously defined here
 volatile bool z_moving = false;
               ^~~~~~~~
src/src/Stepper.cpp:128:18: error: redefinition of 'volatile int32_t jogs'
 volatile int32_t jogs = 0;
                  ^~~~
src/src/Stepper.cpp:31:18: note: 'volatile int32_t jogs' previously defined here
 volatile int32_t jogs = 0;
                  ^~~~
src/src/Stepper.cpp:129:17: error: redefinition of 'volatile double toolRelPos'
 volatile double toolRelPos = 0;
                 ^~~~~~~~~~
src/src/Stepper.cpp:32:17: note: 'volatile double toolRelPos' previously defined here
 volatile double toolRelPos = 0;
                 ^~~~~~~~~~
src/src/Stepper.cpp:130:8: error: redefinition of 'double oldToolRelPosMM'
 double oldToolRelPosMM = 0;
        ^~~~~~~~~~~~~~~
src/src/Stepper.cpp:33:8: note: 'double oldToolRelPosMM' previously defined here
 double oldToolRelPosMM = 0;
        ^~~~~~~~~~~~~~~
src/src/Stepper.cpp:131:17: error: redefinition of 'volatile double targetToolRelPos'
 volatile double targetToolRelPos = 0;
                 ^~~~~~~~~~~~~~~~
src/src/Stepper.cpp:34:17: note: 'volatile double targetToolRelPos' previously defined here
 volatile double targetToolRelPos = 0;
                 ^~~~~~~~~~~~~~~~
src/src/Stepper.cpp:133:5: error: redefinition of 'int use_limit'
 int use_limit = false;
     ^~~~~~~~~
src/src/Stepper.cpp:37:5: note: 'int use_limit' previously defined here
 int use_limit = false;
     ^~~~~~~~~
src/src/Stepper.cpp:134:18: error: redefinition of 'volatile int64_t calculated_stepper_pulses'
 volatile int64_t calculated_stepper_pulses=0;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
src/src/Stepper.cpp:38:18: note: 'volatile int64_t calculated_stepper_pulses' previously defined here
 volatile int64_t calculated_stepper_pulses=0;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
src/src/Stepper.cpp:136:15: error: redefinition of 'volatile bool jog_done'
 volatile bool jog_done = true;
               ^~~~~~~~
src/src/Stepper.cpp:40:15: note: 'volatile bool jog_done' previously defined here
 volatile bool jog_done = true;
               ^~~~~~~~
src/src/Stepper.cpp:137:18: error: redefinition of 'volatile int32_t jog_steps'
 volatile int32_t jog_steps = 0;
                  ^~~~~~~~~
src/src/Stepper.cpp:41:18: note: 'volatile int32_t jog_steps' previously defined here
 volatile int32_t jog_steps = 0;
                  ^~~~~~~~~
src/src/Stepper.cpp:138:17: error: redefinition of 'volatile double jog_scaler'
 volatile double jog_scaler = 0.2;
                 ^~~~~~~~~~
src/src/Stepper.cpp:43:17: note: 'volatile double jog_scaler' previously defined here
 volatile double jog_scaler = 0.2;
                 ^~~~~~~~~~
src/src/Stepper.cpp:139:19: error: redefinition of 'volatile uint16_t vel'
 volatile uint16_t vel = 1;
                   ^~~
src/src/Stepper.cpp:44:19: note: 'volatile uint16_t vel' previously defined here
 volatile uint16_t vel = 1;
                   ^~~
src/src/Stepper.cpp:140:17: error: redefinition of 'volatile double stopPos'
 volatile double stopPos = 0;
                 ^~~~~~~
src/src/Stepper.cpp:45:17: note: 'volatile double stopPos' previously defined here
 volatile double stopPos = 0;
                 ^~~~~~~
src/src/Stepper.cpp:141:17: error: redefinition of 'volatile double stopNeg'
 volatile double stopNeg = 0;
                 ^~~~~~~
src/src/Stepper.cpp:46:17: note: 'volatile double stopNeg' previously defined here
 volatile double stopNeg = 0;
                 ^~~~~~~
src/src/Stepper.cpp:142:15: error: redefinition of 'volatile bool useStops'
 volatile bool useStops = false;
               ^~~~~~~~
src/src/Stepper.cpp:47:15: note: 'volatile bool useStops' previously defined here
 volatile bool useStops = true;
               ^~~~~~~~
src/src/Stepper.cpp:143:15: error: redefinition of 'volatile bool stopPosEx'
 volatile bool stopPosEx = false;
               ^~~~~~~~~
src/src/Stepper.cpp:48:15: note: 'volatile bool stopPosEx' previously defined here
 volatile bool stopPosEx = false;
               ^~~~~~~~~
src/src/Stepper.cpp:144:15: error: redefinition of 'volatile bool stopNegEx'
 volatile bool stopNegEx = false;
               ^~~~~~~~~
src/src/Stepper.cpp:49:15: note: 'volatile bool stopNegEx' previously defined here
 volatile bool stopNegEx = false;
               ^~~~~~~~~
src/src/Stepper.cpp:145:14: error: redefinition of 'volatile int exDelta'
Archiving .pio\build\ESPels\libdf9\libYASM.a
 volatile int exDelta = 0;
              ^~~~~~~
src/src/Stepper.cpp:50:14: note: 'volatile int exDelta' previously defined here
 volatile int exDelta = 0;
              ^~~~~~~
src/src/Stepper.cpp:146:15: error: redefinition of 'volatile bool pos_feeding'
 volatile bool pos_feeding = false;
               ^~~~~~~~~~~
src/src/Stepper.cpp:51:15: note: 'volatile bool pos_feeding' previously defined here
 volatile bool pos_feeding = false;
               ^~~~~~~~~~~
src/src/Stepper.cpp:148:19: error: redefinition of 'rmtStepper::State zstepper'
 rmtStepper::State zstepper;
                   ^~~~~~~~
src/src/Stepper.cpp:53:19: note: 'rmtStepper::State zstepper' previously declared here
 rmtStepper::State zstepper;
                   ^~~~~~~~
src/src/hob.cpp: In function 'void HobReadyState()':
src/src/hob.cpp:6:8: error: 'run_mode' was not declared in this scope
     if(run_mode != RunMode::HOB_RUN){
        ^~~~~~~~
src/src/hob.cpp:6:8: note: suggested alternative: 'RunMode'
     if(run_mode != RunMode::HOB_RUN){
        ^~~~~~~~
        RunMode
src/src/hob.cpp:9:9: error: 'el' was not declared in this scope
         el.error("Use HobStopState, invalid state transition");
         ^~
src/src/hob.cpp: In function 'void HobRunState()':
src/src/hob.cpp:17:9: error: 'useStops' was not declared in this scope
         useStops = false;
         ^~~~~~~~
src/src/hob.cpp:17:9: note: suggested alternative: 'getopt'
         useStops = false;
         ^~~~~~~~
         getopt
src/src/hob.cpp:19:9: error: 'jogging' was not declared in this scope
         jogging = true;
         ^~~~~~~
src/src/hob.cpp:20:9: error: 'init_hob_feed' was not declared in this scope
         init_hob_feed();
         ^~~~~~~~~~~~~
src/src/hob.cpp:21:9: error: 'updateMode' was not declared in this scope
         updateMode(RunMode::HOB_RUN);
         ^~~~~~~~~~
src/src/hob.cpp:21:9: note: suggested alternative: 'pinMode'
         updateMode(RunMode::HOB_RUN);
         ^~~~~~~~~~
         pinMode
src/src/hob.cpp: In function 'void HobStopState()':
src/src/hob.cpp:25:9: error: 'useStops' was not declared in this scope
         useStops = true;
         ^~~~~~~~
src/src/hob.cpp:25:9: note: suggested alternative: 'getopt'
         useStops = true;
         ^~~~~~~~
         getopt
Indexing .pio\build\ESPels\libdf9\libYASM.a
src/src/hob.cpp:26:9: error: 'jogging' was not declared in this scope
         jogging = false;
         ^~~~~~~
src/src/hob.cpp:27:9: error: 'feeding' was not declared in this scope
         feeding = false;
         ^~~~~~~
src/src/hob.cpp:27:9: note: suggested alternative: 'readlink'
         feeding = false;
         ^~~~~~~
         readlink
src/src/hob.cpp:28:9: error: 'pos_feeding' was not declared in this scope
         pos_feeding = false;
         ^~~~~~~~~~~
src/src/hob.cpp:29:9: error: 'updateMode' was not declared in this scope
         updateMode(RunMode::HOB_STOP);
         ^~~~~~~~~~
src/src/hob.cpp:29:9: note: suggested alternative: 'pinMode'
         updateMode(RunMode::HOB_STOP);
         ^~~~~~~~~~
         pinMode
Archiving .pio\build\ESPels\lib1f0\libAsyncTCP.a
Indexing .pio\build\ESPels\lib1f0\libAsyncTCP.a
Archiving .pio\build\ESPels\libd32\libFS.a
Indexing .pio\build\ESPels\libd32\libFS.a
src/src/BounceMode.cpp: In function 'void BounceJogState()':
src/src/BounceMode.cpp:47:9: error: 'updateMode' was not declared in this scope
         updateMode(RunMode::BounceJog);
         ^~~~~~~~~~
src/src/BounceMode.cpp:47:9: note: suggested alternative: 'pinMode'
         updateMode(RunMode::BounceJog);
         ^~~~~~~~~~
         pinMode
src/src/web.cpp: In function 'void setRunMode(int)':
src/src/web.cpp:187:9: error: 'HobReadyState' was not declared in this scope
         HobReadyState();
         ^~~~~~~~~~~~~
src/src/web.cpp:187:9: note: suggested alternative: 'sendState'
         HobReadyState();
         ^~~~~~~~~~~~~
         sendState
src/src/web.cpp: In function 'void handleHobRun()':
src/src/web.cpp:356:7: error: 'HobRunState' was not declared in this scope
       HobRunState();
       ^~~~~~~~~~~
src/src/web.cpp:356:7: note: suggested alternative: 'debugState'
       HobRunState();
       ^~~~~~~~~~~
       debugState
src/src/web.cpp: In function 'void handleHobStop()':
src/src/web.cpp:368:3: error: 'HobStopState' was not declared in this scope
   HobStopState();
   ^~~~~~~~~~~~
src/src/web.cpp:368:3: note: suggested alternative: 'startupState'
   HobStopState();
   ^~~~~~~~~~~~
   startupState
Compiling .pio\build\ESPels\libc3a\WiFi\WiFi.cpp.o
Compiling .pio\build\ESPels\libc3a\WiFi\WiFiAP.cpp.o
Compiling .pio\build\ESPels\libc3a\WiFi\WiFiClient.cpp.o
Compiling .pio\build\ESPels\libc3a\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\ESPels\libc3a\WiFi\WiFiMulti.cpp.o
*** [.pio\build\ESPels\src\src\Stepper.cpp.o] Error 1
*** [.pio\build\ESPels\src\src\hob.cpp.o] Error 1
*** [.pio\build\ESPels\src\src\BounceMode.cpp.o] Error 1
*** [.pio\build\ESPels\src\src\web.cpp.o] Error 1
```

**Comment by digiexchris** [comment]
oh it looks like I may have missed committing a change. I'll track that down...

**Comment by digiexchris** [comment]
oh I see the problem, I need to add some includes to hob, I'll push that later tonight.

**Comment by digiexchris** [comment]
Ok it's updated and compiling now.  Just uploaded it to my bench setup but I have to fix some pins since I had to move them away from the jtag pins. Also note it's likely the pins in this commit is different than what you were using, you might have to set it back. Though I recommend staying away from 12 to 18 for interactive debugging reasons (breakpoints are cool!).

Just thought I'd pass this troubleshooting tip along, this comes up a lot when your code compiles but doesn't link. Multiple definitions. It's because the linker can't use the compile-time #pragma once guards. The fix in this case is either 
1: extern it everywhere, which I don't like because then it's getting initialized twice
2: remove the initialization from Control.cpp and add an include to state instead, which has it extern in the .h and initialized in the .cpp.

Or maybe it belongs in Control afterall, since you explained some things for me. So then it becomes move it to the Control.h and remove it from both state files.

image

**Comment by digiexchris** [comment]
the messages you showed were just a missing include, it didn't know what the variable is so it needed the header. Yes, I know C compiler errors are cryptic, and sometimes the problem isn't even on the line it shows.

**Comment by jschoch** [comment]
config.h:7 semicolon issue

with that fixed it builds

**Comment by digiexchris** [comment]
I may have broken something in web, I get a 500 error. Rewiring to fix my jtag adapter so I can look closer.

**Comment by jschoch** [comment]
web's working fine for me with the s3 link.  did your router change the IP?

also  the string should be ws://<IP>/els

**Comment by digiexchris** [comment]
ah, I had /test from somewhere.... same behaviour though with /els. The 500 is interesting though, it's able to connect to something.  It's sending data to the monitor as well as if it's running. . Yes the ip is the same, the monitor spits out the assigned ip once the wifi connects. wish I could get the server side of that error. It's sending data to the monitor. I have had weird problems with this particular esp32 though, I suspect I may have half fried it at some point in the past. I'll wire up a new one. I'm excited for a esp32-c3 to come in, jtag debugging built right in :D

image

**Comment by jschoch** [comment]
the output is the "mode", in this case 0 for startup, and the wifi signal strength.

The "server" here is your browser, just open the developer console: "Control+Shift+C"

it needs to be http, if you try to connect to the S3 url with https it has a fit since the web socket connection is plain http

**Comment by jschoch** [comment]
the dev console output should be like this when it connects:

image

**Comment by digiexchris** [comment]
hah that was it! I should have clued in when it reported an incorrect cross site issue.

**Comment by digiexchris** [comment]
I like the New Jog in the hobbing UI. Just needs a single button for feed continuous or something in a direction and I'd be totally happy with that. I also updated this PR with the semicolon fix. Seems to run well on my bench setup. 



> this stepper lib doesn't have rmt, we want
> 
> :gin66/FastAccelStepper@^0.28.3

ah yes I still need to fix that. I'll do it tomorrow.

**Comment by jschoch** [comment]
Ok, i'll merge it and run cppcheck and clean out a bunch of the old crud tomorrow morning.

**Comment by digiexchris** [comment]
https://youtu.be/KTWCho43wD0 :)

**Comment by digiexchris** [comment]
darn you merged it, I was going to squash my commits and clean up the messages :D

**Pull request merged**
